name       : ffmpeg-chromium-vivaldi-stable
version    : 110.0.5481.100
release    : 9
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-110.0.5481.100.tar.xz : 6d870d690c1f2c41a288011b0149752681077f1459ebe7a4f9215dbfde21f633
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for vivaldi-stable.
description: |
    Chromium's ffmpeg for vivaldi-stable with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
networking : yes
optimize   : no-symbolic
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
    - nodejs
environment: |
    unset LD_AS_NEEDED
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Misc
    %patch -Np0 < $pkgfiles/angle-wayland-include-protocol.patch

    # Bootstrap GN with build config
    python3 tools/clang/scripts/update.py
    python3 tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"

    # Fix missing tools
    mkdir -p third_party/node/linux/node-linux-x64/bin
    ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/usr/share/vivaldi-stable/libffmpeg.so
