name       : ffmpeg-chromium-vivaldi-stable
version    : 102.0.5005.49
release    : 4
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-102.0.5005.49.tar.xz : 62150e6956a24279a34f2a107b6aaa1ef00df8753fb34bf2d514f9a774ae299b
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for vivaldi-stable.
description: |
    Chromium's ffmpeg for vivaldi-stable with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
optimize   : no-symbolic
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
    - nodejs
environment: |
    unset LD_AS_NEEDED
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Misc
    %patch -Np0 < $pkgfiles/unexpire-accelerated-video-decode-flag.patch
    %patch -p1 < $pkgfiles/0001-Unset-no-opaque-pointers.patch
    %patch -p1 < $pkgfiles/0001-Add-missing-include.patch

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"

    # Fix missing tools
    mkdir -p third_party/node/linux/node-linux-x64/bin
    ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/usr/share/vivaldi-stable/libffmpeg.so
